## https://rocket.rs/v0.5-rc/guide/configuration/

## defaults for _all_ profiles
[default]
address = "0.0.0.0"
limits = { form = "64 kB", json = "1 MiB" }

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
port = 5001
## only the `json` key from `default` will be overridden; `form` will remain
limits = { json = "10MiB" }
log_level = "normal"

## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
port = 5000
log_level = "critical"
